"""AutoCFD5 AIML DrivAerML evaluation tools."""

from .constants import DATASET_REPOSITORY, DATASET_REVISION, EVALUATOR_VERSION

__all__ = ["DATASET_REPOSITORY", "DATASET_REVISION", "EVALUATOR_VERSION"]
